# llama 3.2
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_raw0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_raw0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama3.2_context" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_case0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama3.2_context" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_case0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama3.2_casedialogue" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_cd0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama3.2_casedialogue" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_cd0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_baseline" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_baseline0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_baseline" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_baseline0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_combine_dialogue" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_comd0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_comd0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/umls_dialogue" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_mcdiag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/umls_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_mcdiag0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/umls_mc" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_mc0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/umls_mc" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama32_mc0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/llama32_raw1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/llama32_raw3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/llama32_raw5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/llama32_comdiag1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/llama32_comdiag3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/llama32_comdiag5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_baseline" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/llama32_baseline1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_baseline" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/llama32_baseline3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.2-3B-Instruct" --lora_weight "JesseLiu/llama32_baseline" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/llama32_baseline5m.log 2>&1 &
# qwen 2.5


CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_raw0.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_raw0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_case0.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_case0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_casediag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_casediag0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_mcdiag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_mcdiag0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_mc0.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_mc0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline"  --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_baseline0.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline"  --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_baseline0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue"  --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_baseline0.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue"  --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25_baseline0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25_raw1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25_raw3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25_raw5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25_comdiag1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25_comdiag3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25_comdiag5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25_baseline1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25_baseline3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25_baseline5m.log 2>&1 &
# llama 3.1
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_raw0.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_raw0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --lora_weight "rellabear/exp2_llama3.1_8b_context_ep3" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_case0.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --lora_weight "rellabear/exp2_llama3.1_8b_context_ep3" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_case0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --lora_weight "rellabear/exp3_llama3.1_combine_baseline_ep3" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_baseline0.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --lora_weight "rellabear/exp3_llama3.1_combine_baseline_ep3" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_baseline0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --lora_weight "rellabear/exp3_llama3.1_combine_dialogue_ep3" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_comdiag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --lora_weight "rellabear/exp3_llama3.1_combine_dialogue_ep3" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_comdiag0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp2_llama3.1_8b_dialogue_ep3" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_casediag0.log 2>&1 &



CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp2_llama3.1_8b_dialogue_ep3" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_casediag0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/dialogue_llama8b_umls" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_mcdiag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/dialogue_llama8b_umls" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_mcdiag0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/mc_llama_8b" --output_path "./output" --task_type "one_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_mc0.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/mc_llama_8b" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/llama31_mc0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/llama31_raw1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/llama31_raw3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/llama31_raw5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp3_llama3.1_combine_baseline_ep3" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/llama31_baseline1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp3_llama3.1_combine_baseline_ep3" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/llama31_baseline3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp3_llama3.1_combine_baseline_ep3" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/llama31_baseline5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp3_llama3.1_combine_dialogue_ep3" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/llama31_comdiag1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp3_llama3.1_combine_dialogue_ep3" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/llama31_comdiag3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "meta-llama/Llama-3.1-8B-Instruct" --lora_weight "rellabear/exp3_llama3.1_combine_dialogue_ep3" --output_path "./output" --task_type "multi_round" --task_name 'llama' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/llama31_comdiag5m.log 2>&1 &

# mistral
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_raw0.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_raw0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --lora_weight "rellabear/exp3_mistral7b_combine_baseline_ep2" --output_path "./output" --task_type "one_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_baseline0.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --lora_weight "rellabear/exp3_mistral7b_combine_baseline_ep2" --output_path "./output" --task_type "multi_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_baseline0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --output_path "./output" --task_type "one_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_comdiag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --output_path "./output" --task_type "multi_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_comdiag0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "rellabear/exp2_mistral7b_dialogue_ep2" --task_type "one_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_cd0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "rellabear/exp2_mistral7b_dialogue_ep2" --task_type "multi_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_cd0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "rellabear/exp2_mistral7b_context_ep2" --task_type "one_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_case0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "rellabear/exp2_mistral7b_context_ep2" --task_type "multi_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_case0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "JesseLiu/mistral7b_mc_ep1" --task_type "one_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_mc0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "JesseLiu/mistral7b_mc_ep1" --task_type "multi_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_mc0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "JesseLiu/mistral7b_dialogue" --task_type "one_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_mcdiag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --lora_weight "JesseLiu/mistral7b_dialogue" --task_type "multi_round" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_mcdiag0m.log 2>&1 &

