CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_ct0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/mistral_ct1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/mistral_ct3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/mistral_ct5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_diag0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/mistral_diag1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/mistral_diag3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/mistral_diag5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_ct0.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/mistral_ct1.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/mistral_ct3.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_context_ep2" --task_name 'mistral' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/mistral_ct5.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_diag0.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/mistral_diag1.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/mistral_diag3.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/mistral7b_dialogue_ep2" --task_name 'mistral' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/mistral_diag5.log 2>&1 &


CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_cd0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_cd0m.log 2>&1 &


CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/exp3_mistral7b_combine_baseline_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_cd0.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/mistral_diag1.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/mistral_diag3.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "one_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/mistral_diag5.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/exp3_mistral7b_combine_baseline_ep2" --task_name 'mistral' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/mistral_cd0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/mistral_diag1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/mistral_diag3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "mistralai/Mistral-7B-Instruct-v0.3" --output_path "./output" --task_type "multi_round" --lora_weight "rellabear/exp3_mistral7b_combine_dialogue_ep2" --task_name 'mistral' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/mistral_diag5m.log 2>&1 &