CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25C_3B_0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25C_3B_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25C_3B_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25C_3B_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25C_3B_0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25C_3B_1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25C_3B_3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen2.5_context" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25C_3B_5m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25D_3B_0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25D_3B_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25D_3B_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25D_3B_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25D_3B_0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25D_3B_1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25D_3B_3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_casedialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25D_3B_5m.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25DC_3B_0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25DC_3B_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25DC_3B_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25DC_3B_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25DC_3B_0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25DC_3B_1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25DC_3B_3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25DC_3B_5m.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25CC_3B_0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25CC_3B_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25CC_3B_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "one_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25CC_3B_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25CC_3B_0m.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25CC_3B_1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25CC_3B_3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_mc" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25CC_3B_5m.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "one_round" --lora_weight "JesseLiu/qwen3b_baseline" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25ba_3B_0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "multi_round" --lora_weight "JesseLiu/qwen3b_baseline" --task_name 'qwen' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25ba_3B_0m.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "one_round" --lora_weight "JesseLiu/qwen25_combine_dialogue" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25ba_cd0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --output_path "./output" --task_type "multi_round" --lora_weight "JesseLiu/qwen25_combine_dialogue" --task_name 'llama' --confusion_level 0 --num_fewshot 0 --config 'cl_0' > ./log/qwen25ba_cdm0.log 2>&1 &

CUDA_VISIBLE_DEVICES=6 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25_3B_1.log 2>&1 &

CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25_3B_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen3b_baseline" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25_3B_5.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 1 --num_fewshot 0 --config 'cl_1' > ./log/qwen25_3B_1m.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 3 --num_fewshot 0 --config 'cl_3' > ./log/qwen25_3B_3m.log 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup python main.py --model "hf" --model_args "Qwen/Qwen2.5-3B-Instruct" --lora_weight "JesseLiu/qwen25_combine_dialogue" --output_path "./output" --task_type "multi_round" --task_name 'qwen' --confusion_level 5 --num_fewshot 0 --config 'cl_5' > ./log/qwen25_3B_5m.log 2>&1 &
